---
title: "Analyzing the 2014 Toronto Mayoral Election"
author: "Matthew Routley and Matt DesRosiers"
date: "July 7, 2014"
output: html_document
---

A specific but lofty goal
=========================

Campaigns have limited resources – both time and financial – that should be spent on attracting voters that are more likely to support their candidates. Identifying these voters can be critical to the success of a candidate
Given the privacy of voting and the lack of useful surveys at the municipal level, there are few options for identifying voter preferences:
City-wide polling, which is large-scale but does nothing to identify voters
Voter databases, which identify individual voters, but are small scale
In-depth analytical modeling, which is both large-scale and helps to 'identify' voters at a neighbourhood level on average

￼GOAL: To effectively model – at a neighbourhood level – which candidates voters are likely to support, specifically in the 2014 Toron mayoral race

Voters aren’t stuck in their ways
=================================

Voters have revealed that their preferences aren’t stuck in stone

Are voters changing positions or voting strategically (and are those the same?), or is it simply that different voters are showing up?

To try to separate out the latter, we looked at turnout, and specifically areas where turnout is above 60% in all three elections to see if those areas change positions. Turns out that they do (by close to 0.1 on the position scale, on average) – suggesting that it’s not simply voters waiting for the 'right' candidate to come along

Proximity voting and calibration
================================

The theory of ‘proximity’ voting (see appendix); and
A ‘voteability' variable to calibrate to the most recent polls. 'Voteability' includes numerous factors, including:

How well known is/are the candidate and their positions
How'likeable'/'trustworthy'isthecandidate
Perceived viability of the candidate winning
Whether voters are voting strategically (e.g., choosing the 'lesser of two evils' if their preferred choice is perceived to be unviable)

This does not yet say why voters vote the way they do (which we hope comes next as we add additional complexity), but does identify where those voters may be

Current challenge for Tory is 'Voteability'
===========================================

If strictly based on currently* stated positions, John Tory would win a three- way election, easily beating Chow and Ford (48%, 38%, and 14% of the votes)

This assumes that all issues are equally important to voters However, calibrating to recent polls** suggests that John Tory’s current
‘voteability’ is relatively low (~ 60% of Chow and 33% of Ford)
Taking this into account, the election – if held today – might see the following number of votes cast for each of the three 'main' candidates:

Scenarios
=========

At this point, we can still conduct useful scenarios. These show how changes in candidates’ positions and voteability scores would impact high-level and geographic breakdown of support
As examples, Tory just wins (all other things unchanged) when his voteability score increases by:
34% (still less than Chow and much less than Ford), or
9%, if Ford drops out of the race, or
0%, if he moves 5 “points” to the left, forcing Chow to do the same

A couple issues have been important
===================================

Over the last three elections, various issues have been influential in the way wards have voted, but a few key issues certainly stand out:
￼Island airport expansion: Top issue overall; top issue in 30 wards; close second in another 6. Voters have typically voted against expansion
Transportation (roads and bike lanes): Top issue in 10 wards; close second in another 6. Votes split depending on ward
Finance and budget, transit, waste management, and other issues have been much less important historically

If these issues were still important...
=======================================

If voters placed the same importance on issues as they have over the last three elections (i.e., not weighted equally as on slide 10), then strictly based on currently* stated positions, Chow would narrowly beat Tory:

Neighbourhood characteristics are predictive
============================================

Based on 2011 Census data, there are three general components that are modestly correlated with voting over the last three elections. If these hold in 2014, neighbourhoods that are predominantly:

Core and GOTV areas
===================

Based on a combination of issue importance (by ward) and “directional positional alignment” with Tory (e.g., both his and the ward’s average position on topic X are right or left), we have identified two types of areas:
"Core” areas – highly directionally aligned and average turnout is relatively high (>52.5%)
“Get-out-the-vote” (GOTV) areas – highly directionally aligned and average turnout is low (<30%)
Each group has roughly 50 areas (see attached spreadsheet) and contains ~45,000 and 130,000 eligible voters, respectively
For example, an additional 5% turnout in these GOTV areas, all voting for Tory, would provide 6,500 votes (or ~1% of the average number of votes)