library(dplyr)
library(RSQLite)
library(RSQLite.extfuns)
elections_db <- src_sqlite("data/elections_db.sqlite3", create = T)
votes <- read.csv(file="data//election_results.csv")
copy_to(elections_db, votes, temporary = FALSE, indexes = list("year", c("ward", "area"), "candidate"))
turnout <- read.csv(file="data//turnout.csv") %.%
                  select(-(ID))
copy_to(elections_db, turnout, temporary = FALSE, indexes = list("year", c("ward", "area")))
age_sex <- read.csv(file="data//toronto_census_age_sex.csv")
copy_to(elections_db, age_sex, temporary = FALSE, indexes = list(c("SGC", "census")))
census <- read.csv(file="data//census.csv") %.%
  select(-c(CMA_CA_Name,Note))
copy_to(elections_db, census, temporary = FALSE, indexes = list(c("GEO", "census")))
locations <- read.csv(file="data//voting_locations.csv")
copy_to(elections_db, locations, temporary = FALSE, indexes = list("CTUID", "year",c("ward","area")))
family_income <- read.csv(file="data//census_2006_family_income.csv")
copy_to(elections_db, family_income, temporary = FALSE, indexes = list("SGC",c("income_type","family_structure")))
rm(votes,turnout,age_sex,census,locations,family_income)
